# Addon name
ADDON = "auto_sync_lingq"
LANGUAGE_CODES = {
    "Czech": "cs",
    "Norwegian": "no",
    "Turkish": "tr",
    "Finnish": "fi",
    "Hebrew": "he",
    "Romanian": "ro",
    "Dutch": "nl",
    "Greek": "el",
    "Polish": "pl",
    "Esperanto": "eo",
    "Latin": "la",
    "Danish": "da",
    "Ukrainian": "uk",
    "Slovak": "sk",
    "Malay": "ms",
    "Indonesian": "id",
    "Chinese (Traditional)": "zh-t",
    "Cantonese": "hk",
    "Gujarati": "gu",
    "Bulgarian": "bg",
    "Persian": "fa",
    "Belarusian": "be",
    "Arabic": "ar",
    "Serbian": "srp",
    "Croatian": "hrv",
    "Hungarian": "hu",
    "Catalan": "ca",
    "English": "en",
    "French": "fr",
    "German": "de",
    "Spanish": "es",
    "Italian": "it",
    "Japanese": "ja",
    "Korean": "ko",
    "Chinese": "zh",
    "Portuguese": "pt",
    "Russian": "ru",
    "Swedish": "sv",
}